-- MAIN PAGE IMAGE 파일의 정보를 저장할 테이블
CREATE TABLE M_IMAGE(
	IMAGE_ID NUMBER PRIMARY KEY,
	ARTIST_ID NUMBER NOT NULL,
	ARTIST_NAME VARCHAR2(255) NOT NULL,
	ARTIST_E_NAME VARCHAR2(255) NOT NULL,
	IMAGE_NAME CLOB NOT NULL
);	
-- M_IMAGE 테이블에서 사용할 시퀀스
CREATE SEQUENCE M_IMAGE_SEQ;
CREATE SEQUENCE M_IMAGE_ARTIST_ID_SEQ;

-- MAIN PAGE MUSIC VIDEO 의 정보를 저장할 테이블
CREATE TABLE M_MUSICVIDEO(
	MUSICVIDEO_ID NUMBER PRIMARY KEY,
	ARTIST_ID NUMBER NOT NULL,
	ARTIST_E_NAME VARCHAR2(255) NOT NULL,
	MUSICVIDEO_NAME VARCHAR2(255) NOT NULL,
	MUSICVIDEO_LINK CLOB NOT NULL,
	MUSICVIDEO_THUMBNAIL_NAME CLOB NOT NULL
);
-- M_MUSICVIDEO 테이블에서 사용할 시퀀스
CREATE SEQUENCE M_MUSICVIDEO_SEQ;

-- M_NEWS 의 정보를 저장할 테이블
CREATE TABLE M_NEWS(
	NEWS_ID NUMBER PRIMARY KEY,
	ARTIST_ID NUMBER NOT NULL,
	ARTIST_NAME VARCHAR2(255) NOT NULL,
	ARTIST_E_NAME VARCHAR2(255) NOT NULL,
	NEWS_WRITER VARCHAR2(255) NOT NULL,
	NEWS_TITLE VARCHAR2(255) NOT NULL,
	NEWS_CONTENT CLOB NOT NULL,
	NEWS_REGDATE DATE NOT NULL,
	IMAGE_NAME CLOB NOT NULL	
);
-- M_NEWS 테이블에서 사용할 시퀀스
CREATE SEQUENCE M_NEWS_SEQ;

-- M_OFFICIALCHANNEL 의 정보를 저장할 테이블
CREATE TABLE M_OFFICIALCHANNEL(
	OFFICIALCHANNEL_ID NUMBER PRIMARY KEY,
	OFFICIALCHANNEL_LINK VARCHAR2(255) NOT NULL,
	OFFICIALCHANNEL_ICON_NAME VARCHAR2(255) NOT NULL
);
-- M_OFFICIALCHANNEL 테이블에서 사용할 시퀀스
CREATE SEQUENCE M_OFFICIALCHANNEL_SEQ;

-- M_PLAYLIST 의 정보를 저장할 테이블
CREATE TABLE M_PLAYLIST(
	PLAYLIST_ID NUMBER PRIMARY KEY,
	PLAYLIST_WRITER VARCHAR2(255) NOT NULL,
	PLAYLIST_TITLE VARCHAR2(255) NOT NULL,
	PLAYLIST_LINK CLOB NOT NULL,
	IMAGE_NAME CLOB NOT NULL,
	PLAYLIST_LIST1 VARCHAR2(255) NOT NULL,
	PLAYLIST_LIST2 VARCHAR2(255) NOT NULL,
	PLAYLIST_LIST3 VARCHAR2(255) NOT NULL,
	PLAYLIST_LIST4 VARCHAR2(255) NOT NULL,
	PLAYLIST_LIST5 VARCHAR2(255) NOT NULL
);
-- M_PLAYLIST 테이블에서 사용할 시퀀스
CREATE SEQUENCE M_PLAYLIST_SEQ;

-- M_ARTIST 의 정보를 저장할 테이블
CREATE TABLE M_ARTIST(
	ARTIST_ID NUMBER PRIMARY KEY,
	ARTIST_NAME VARCHAR2(255) NOT NULL,
	ARTIST_E_NAME VARCHAR2(255) NOT NULL,
	IMAGE_NAME CLOB NOT NULL,
	ARTIST_COUNTRY VARCHAR2(255) NOT NULL,
	ARTIST_DESCRIPTION CLOB NOT NULL
);
-- M_ARTIST 테이블에서 사용할 시퀀스
CREATE SEQUENCE M_ARTIST_SEQ;

-- M_INSTAFEED 의 정보를 저장할 테이블
CREATE TABLE M_INSTAFEED(
	INSTAFEED_ID NUMBER PRIMARY KEY,
	INSTAFEED_LINK CLOB NOT NULL,
	IMAGE_NAME CLOB NOT NULL
);
-- M_INSTAFEED 테이블에서 사용할 시퀀스
CREATE SEQUENCE M_INSTAFEED_SEQ;